// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type User struct {
	ID           int64     `json:"id"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	FirstName    string    `json:"firstName"`
	LastName     string    `json:"lastName"`
	DisplayName  string    `json:"displayName"`
	PasswordHash string    `json:"passwordHash"`
	PictureURL   *string   `json:"pictureUrl"`
	TOTPSecret   *string   `json:"totpSecret"`
}
