// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"
)

type Permission struct {
	ID       int64  `json:"id"`
	Resource string `json:"resource"`
	Method   string `json:"method"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RolePermission struct {
	RoleID       int64 `json:"roleId"`
	PermissionID int64 `json:"permissionId"`
}

type User struct {
	ID           int64     `json:"id"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
	FirstName    string    `json:"firstName"`
	LastName     string    `json:"lastName"`
	DisplayName  string    `json:"displayName"`
	PasswordHash string    `json:"passwordHash"`
	PictureURL   *string   `json:"pictureUrl"`
	TOTPSecret   *string   `json:"totpSecret"`
}

type UserRole struct {
	UserID int64 `json:"userId"`
	RoleID int64 `json:"roleId"`
}
