// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package database

import (
	"context"
)

const listPermissions = `-- name: ListPermissions :many
SELECT p.id, p.resource, p.method
  FROM permissions AS p
 WHERE p.id > ?1
 ORDER BY p.id ASC
 LIMIT ?2
`

type ListPermissionsParams struct {
	After int64 `json:"after"`
	First int64 `json:"first"`
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]*Permission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions, arg.After, arg.First)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Resource, &i.Method); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPermission = `-- name: UpsertPermission :execrows
INSERT INTO permissions (id, resource, method)
VALUES (?1, ?2, ?3)
ON CONFLICT DO UPDATE
SET resource = ?2,
    method = ?3
WHERE id = ?1
`

type UpsertPermissionParams struct {
	ID       int64  `json:"id"`
	Resource string `json:"resource"`
	Method   string `json:"method"`
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertPermission, arg.ID, arg.Resource, arg.Method)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
