// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	FindUserByDisplayName(ctx context.Context, arg FindUserByDisplayNameParams) (*User, error)
	FindUserByID(ctx context.Context, arg FindUserByIDParams) (*User, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
