// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	FindUserByID(ctx context.Context, db DBTX, arg FindUserByIDParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
