// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package database

import (
	"context"
)

const findRoleByID = `-- name: FindRoleByID :one
SELECT r.id, r.name
  FROM roles AS r
 WHERE r.id = ?1
 LIMIT 1
`

type FindRoleByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) FindRoleByID(ctx context.Context, arg FindRoleByIDParams) (*Role, error) {
	row := q.db.QueryRowContext(ctx, findRoleByID, arg.ID)
	var i Role
	err := row.Scan(&i.ID, &i.Name)
	return &i, err
}

const listRoles = `-- name: ListRoles :many
SELECT r.id, r.name
  FROM roles AS r
 WHERE r.name > ?1
 ORDER BY r.name ASC
 LIMIT ?2
`

type ListRolesParams struct {
	After string `json:"after"`
	First int64  `json:"first"`
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]*Role, error) {
	rows, err := q.db.QueryContext(ctx, listRoles, arg.After, arg.First)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRole = `-- name: UpsertRole :execrows
INSERT INTO roles (name)
VALUES (?1)
ON CONFLICT DO NOTHING
`

type UpsertRoleParams struct {
	Name string `json:"name"`
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertRole, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
