// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
)

const findUserByID = `-- name: FindUserByID :one
SELECT u.id, u.created_at, u.updated_at, u.first_name, u.last_name, u.display_name, u.password_hash, u.picture_url, u.totp_secret
FROM users AS u
WHERE u.id = ?1
LIMIT 1
`

type FindUserByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) FindUserByID(ctx context.Context, db DBTX, arg FindUserByIDParams) (*User, error) {
	row := db.QueryRowContext(ctx, findUserByID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PictureURL,
		&i.TOTPSecret,
	)
	return &i, err
}
