// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package database

import (
	"context"
)

const findUserByDisplayName = `-- name: FindUserByDisplayName :one
SELECT u.id, u.created_at, u.updated_at, u.first_name, u.last_name, u.display_name, u.password_hash, u.picture_url, u.totp_secret
FROM users AS u
WHERE u.display_name = ?1
LIMIT 1
`

type FindUserByDisplayNameParams struct {
	DisplayName string `json:"displayName"`
}

func (q *Queries) FindUserByDisplayName(ctx context.Context, arg FindUserByDisplayNameParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, findUserByDisplayName, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PictureURL,
		&i.TOTPSecret,
	)
	return &i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT u.id, u.created_at, u.updated_at, u.first_name, u.last_name, u.display_name, u.password_hash, u.picture_url, u.totp_secret
FROM users AS u
WHERE u.id = ?1
LIMIT 1
`

type FindUserByIDParams struct {
	ID int64 `json:"id"`
}

func (q *Queries) FindUserByID(ctx context.Context, arg FindUserByIDParams) (*User, error) {
	row := q.db.QueryRowContext(ctx, findUserByID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PictureURL,
		&i.TOTPSecret,
	)
	return &i, err
}

const upsertUser = `-- name: UpsertUser :execrows
INSERT INTO users
(
	first_name,
	last_name,
	display_name,
	password_hash,
	picture_url,
	totp_secret
)
VALUES
(
	?1,
	?2,
	?3,
	?4,
	?5,
	?6
) ON CONFLICT (display_name) DO UPDATE 
  SET updated_at = DATETIME('now'),
      first_name = ?1,
      last_name = ?2,
      password_hash = ?4,
      picture_url = ?5,
      totp_secret = ?6
WHERE display_name = ?3
`

type UpsertUserParams struct {
	FirstName    string  `json:"firstName"`
	LastName     string  `json:"lastName"`
	DisplayName  string  `json:"displayName"`
	PasswordHash string  `json:"passwordHash"`
	PictureURL   *string `json:"pictureUrl"`
	TOTPSecret   *string `json:"totpSecret"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, upsertUser,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.PasswordHash,
		arg.PictureURL,
		arg.TOTPSecret,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
