/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BreadcrumbList: typeof import('./components/breadcrumb-list.vue')['default']
    DefaultHeader: typeof import('./components/default-header.vue')['default']
    DefaultNavbar: typeof import('./components/default-navbar.vue')['default']
    DefaultSidebar: typeof import('./components/default-sidebar.vue')['default']
    FormControl: typeof import('./components/form-control.vue')['default']
    LoadingSpinner: typeof import('./components/loading-spinner.vue')['default']
    ProfileMenu: typeof import('./components/profile-menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
