/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
    import type {
        RouteRecordInfo,
        ParamValue,
        ParamValueOneOrMore,
        ParamValueZeroOrMore,
        ParamValueZeroOrOne,
    } from 'vue-router';

    /**
     * Route name map generated by unplugin-vue-router
     */
    export interface RouteNamedMap {
        '/': RouteRecordInfo<
            '/',
            '/',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/host/': RouteRecordInfo<
            '/host/',
            '/host',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/host/[host]': RouteRecordInfo<
            '/host/[host]',
            '/host/:host',
            { host: ParamValue<true> },
            { host: ParamValue<false> },
            | '/host/[host]/'
            | '/host/[host]/instance/'
            | '/host/[host]/instance/[instance]'
            | '/host/[host]/instance/[instance]/'
            | '/host/[host]/instance/[instance]/properties'
            | '/host/[host]/instance/[instance]/whitelist'
        >;
        '/host/[host]/': RouteRecordInfo<
            '/host/[host]/',
            '/host/:host',
            { host: ParamValue<true> },
            { host: ParamValue<false> },
            never
        >;
        '/host/[host]/instance/': RouteRecordInfo<
            '/host/[host]/instance/',
            '/host/:host/instance',
            { host: ParamValue<true> },
            { host: ParamValue<false> },
            never
        >;
        '/host/[host]/instance/[instance]': RouteRecordInfo<
            '/host/[host]/instance/[instance]',
            '/host/:host/instance/:instance',
            { host: ParamValue<true>; instance: ParamValue<true> },
            { host: ParamValue<false>; instance: ParamValue<false> },
            | '/host/[host]/instance/[instance]/'
            | '/host/[host]/instance/[instance]/properties'
            | '/host/[host]/instance/[instance]/whitelist'
        >;
        '/host/[host]/instance/[instance]/': RouteRecordInfo<
            '/host/[host]/instance/[instance]/',
            '/host/:host/instance/:instance',
            { host: ParamValue<true>; instance: ParamValue<true> },
            { host: ParamValue<false>; instance: ParamValue<false> },
            never
        >;
        '/host/[host]/instance/[instance]/properties': RouteRecordInfo<
            '/host/[host]/instance/[instance]/properties',
            '/host/:host/instance/:instance/properties',
            { host: ParamValue<true>; instance: ParamValue<true> },
            { host: ParamValue<false>; instance: ParamValue<false> },
            never
        >;
        '/host/[host]/instance/[instance]/whitelist': RouteRecordInfo<
            '/host/[host]/instance/[instance]/whitelist',
            '/host/:host/instance/:instance/whitelist',
            { host: ParamValue<true>; instance: ParamValue<true> },
            { host: ParamValue<false>; instance: ParamValue<false> },
            never
        >;
        '/user/': RouteRecordInfo<
            '/user/',
            '/user',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/user/(auth)/login': RouteRecordInfo<
            '/user/(auth)/login',
            '/user/login',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/user/(auth)/logout': RouteRecordInfo<
            '/user/(auth)/logout',
            '/user/logout',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/user/(auth)/recovery': RouteRecordInfo<
            '/user/(auth)/recovery',
            '/user/recovery',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/user/[id]': RouteRecordInfo<
            '/user/[id]',
            '/user/:id',
            { id: ParamValue<true> },
            { id: ParamValue<false> },
            never
        >;
        '/user/profile': RouteRecordInfo<
            '/user/profile',
            '/user/profile',
            Record<never, never>,
            Record<never, never>,
            never
        >;
    }

    /**
     * Route file to route info map by unplugin-vue-router.
     * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
     *
     * Each key is a file path relative to the project root with 2 properties:
     * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
     * - views: names of nested views (can be passed to <RouterView name="...">)
     *
     * @internal
     */
    export interface _RouteFileInfoMap {
        'src/pages/index.vue': {
            routes: '/';
            views: never;
        };
        'src/pages/host/index.vue': {
            routes: '/host/';
            views: never;
        };
        'src/pages/host/[host].vue': {
            routes:
                | '/host/[host]'
                | '/host/[host]/'
                | '/host/[host]/instance/'
                | '/host/[host]/instance/[instance]'
                | '/host/[host]/instance/[instance]/'
                | '/host/[host]/instance/[instance]/properties'
                | '/host/[host]/instance/[instance]/whitelist';
            views: 'default';
        };
        'src/pages/host/[host]/index.vue': {
            routes: '/host/[host]/';
            views: never;
        };
        'src/pages/host/[host]/instance/index.vue': {
            routes: '/host/[host]/instance/';
            views: never;
        };
        'src/pages/host/[host]/instance/[instance].vue': {
            routes:
                | '/host/[host]/instance/[instance]'
                | '/host/[host]/instance/[instance]/'
                | '/host/[host]/instance/[instance]/properties'
                | '/host/[host]/instance/[instance]/whitelist';
            views: 'default';
        };
        'src/pages/host/[host]/instance/[instance]/index.vue': {
            routes: '/host/[host]/instance/[instance]/';
            views: never;
        };
        'src/pages/host/[host]/instance/[instance]/properties.vue': {
            routes: '/host/[host]/instance/[instance]/properties';
            views: never;
        };
        'src/pages/host/[host]/instance/[instance]/whitelist.vue': {
            routes: '/host/[host]/instance/[instance]/whitelist';
            views: never;
        };
        'src/pages/user/index.vue': {
            routes: '/user/';
            views: never;
        };
        'src/pages/user/(auth)/login.vue': {
            routes: '/user/(auth)/login';
            views: never;
        };
        'src/pages/user/(auth)/logout.vue': {
            routes: '/user/(auth)/logout';
            views: never;
        };
        'src/pages/user/(auth)/recovery.vue': {
            routes: '/user/(auth)/recovery';
            views: never;
        };
        'src/pages/user/[id].vue': {
            routes: '/user/[id]';
            views: never;
        };
        'src/pages/user/profile.vue': {
            routes: '/user/profile';
            views: never;
        };
    }

    /**
     * Get a union of possible route names in a certain route component file.
     * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
     *
     * @internal
     */
    export type _RouteNamesForFilePath<FilePath extends string> =
        _RouteFileInfoMap extends Record<FilePath, infer Info>
            ? Info['routes']
            : keyof RouteNamedMap;
}
