/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<
      'home',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'hosts-layout': RouteRecordInfo<
      'hosts-layout',
      '/host',
      Record<never, never>,
      Record<never, never>,
      | 'host'
      | 'host-instances'
      | 'host-layout'
      | 'host-metrics'
      | 'hosts'
      | 'instance'
      | 'instance-layout'
      | 'instance-properties'
      | 'instance-whitelist'
    >,
    'hosts': RouteRecordInfo<
      'hosts',
      '/host',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'host-layout': RouteRecordInfo<
      'host-layout',
      '/host/:host',
      { host: ParamValue<true> },
      { host: ParamValue<false> },
      | 'host'
      | 'host-instances'
      | 'host-metrics'
      | 'instance'
      | 'instance-layout'
      | 'instance-properties'
      | 'instance-whitelist'
    >,
    'host': RouteRecordInfo<
      'host',
      '/host/:host',
      { host: ParamValue<true> },
      { host: ParamValue<false> },
      | never
    >,
    'host-instances': RouteRecordInfo<
      'host-instances',
      '/host/:host/instance',
      { host: ParamValue<true> },
      { host: ParamValue<false> },
      | never
    >,
    'instance-layout': RouteRecordInfo<
      'instance-layout',
      '/host/:host/instance/:instance',
      { host: ParamValue<true>, instance: ParamValue<true> },
      { host: ParamValue<false>, instance: ParamValue<false> },
      | 'instance'
      | 'instance-properties'
      | 'instance-whitelist'
    >,
    'instance': RouteRecordInfo<
      'instance',
      '/host/:host/instance/:instance',
      { host: ParamValue<true>, instance: ParamValue<true> },
      { host: ParamValue<false>, instance: ParamValue<false> },
      | never
    >,
    'instance-properties': RouteRecordInfo<
      'instance-properties',
      '/host/:host/instance/:instance/properties',
      { host: ParamValue<true>, instance: ParamValue<true> },
      { host: ParamValue<false>, instance: ParamValue<false> },
      | never
    >,
    'instance-whitelist': RouteRecordInfo<
      'instance-whitelist',
      '/host/:host/instance/:instance/whitelist',
      { host: ParamValue<true>, instance: ParamValue<true> },
      { host: ParamValue<false>, instance: ParamValue<false> },
      | never
    >,
    'host-metrics': RouteRecordInfo<
      'host-metrics',
      '/host/:host/metrics',
      { host: ParamValue<true> },
      { host: ParamValue<false> },
      | never
    >,
    'user-layout': RouteRecordInfo<
      'user-layout',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | 'login'
      | 'logout'
      | 'profile'
      | 'recovery'
      | 'user'
      | 'users'
    >,
    'users': RouteRecordInfo<
      'users',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'login': RouteRecordInfo<
      'login',
      '/user/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'logout': RouteRecordInfo<
      'logout',
      '/user/logout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'profile': RouteRecordInfo<
      'profile',
      '/user/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'recovery': RouteRecordInfo<
      'recovery',
      '/user/recovery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'user': RouteRecordInfo<
      'user',
      '/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'home'
      views:
        | never
    }
    'src/pages/host.vue': {
      routes:
        | 'host'
        | 'host-instances'
        | 'host-layout'
        | 'host-metrics'
        | 'hosts'
        | 'hosts-layout'
        | 'instance'
        | 'instance-layout'
        | 'instance-properties'
        | 'instance-whitelist'
      views:
        | 'default'
    }
    'src/pages/host/index.vue': {
      routes:
        | 'hosts'
      views:
        | never
    }
    'src/pages/host/[host].vue': {
      routes:
        | 'host'
        | 'host-instances'
        | 'host-layout'
        | 'host-metrics'
        | 'instance'
        | 'instance-layout'
        | 'instance-properties'
        | 'instance-whitelist'
      views:
        | 'default'
    }
    'src/pages/host/[host]/index.vue': {
      routes:
        | 'host'
      views:
        | never
    }
    'src/pages/host/[host]/instance/index.vue': {
      routes:
        | 'host-instances'
      views:
        | never
    }
    'src/pages/host/[host]/instance/[instance].vue': {
      routes:
        | 'instance'
        | 'instance-layout'
        | 'instance-properties'
        | 'instance-whitelist'
      views:
        | 'default'
    }
    'src/pages/host/[host]/instance/[instance]/index.vue': {
      routes:
        | 'instance'
      views:
        | never
    }
    'src/pages/host/[host]/instance/[instance]/properties.vue': {
      routes:
        | 'instance-properties'
      views:
        | never
    }
    'src/pages/host/[host]/instance/[instance]/whitelist.vue': {
      routes:
        | 'instance-whitelist'
      views:
        | never
    }
    'src/pages/host/[host]/metrics.vue': {
      routes:
        | 'host-metrics'
      views:
        | never
    }
    'src/pages/user.vue': {
      routes:
        | 'login'
        | 'logout'
        | 'profile'
        | 'recovery'
        | 'user'
        | 'user-layout'
        | 'users'
      views:
        | 'default'
    }
    'src/pages/user/index.vue': {
      routes:
        | 'users'
      views:
        | never
    }
    'src/pages/user/(auth)/login.vue': {
      routes:
        | 'login'
      views:
        | never
    }
    'src/pages/user/(auth)/logout.vue': {
      routes:
        | 'logout'
      views:
        | never
    }
    'src/pages/user/(auth)/profile.vue': {
      routes:
        | 'profile'
      views:
        | never
    }
    'src/pages/user/(auth)/recovery.vue': {
      routes:
        | 'recovery'
      views:
        | never
    }
    'src/pages/user/[id].vue': {
      routes:
        | 'user'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
