// Code generated by "stringer -type Status -linecomment -trimprefix Status"; DO NOT EDIT.

package linode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusRunning-0]
	_ = x[StatusOffline-1]
	_ = x[StatusBooting-2]
	_ = x[StatusRebooting-3]
	_ = x[StatusShuttingDown-4]
	_ = x[StatusStopped-5]
	_ = x[StatusBillingSuspension-6]
}

const _Status_name = "runningofflinebootingrebootingshutting_downstoppedbilling_suspension"

var _Status_index = [...]uint8{0, 7, 14, 21, 30, 43, 50, 68}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
