// Code generated by "stringer -type Topic -trimprefix Topic"; DO NOT EDIT.

package linode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TopicStatus-0]
	_ = x[TopicBoot-1]
	_ = x[TopicReboot-2]
	_ = x[TopicShutdown-3]
}

const _Topic_name = "StatusBootRebootShutdown"

var _Topic_index = [...]uint8{0, 6, 10, 16, 24}

func (i Topic) String() string {
	if i < 0 || i >= Topic(len(_Topic_index)-1) {
		return "Topic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Topic_name[_Topic_index[i]:_Topic_index[i+1]]
}
