shellEmulator: true

trustPolicy: no-downgrade

packages:
    - web/app

catalogs:
    build:
        '@iconify-json/solar': ^1.2.5
        '@iconify/tailwind4': ^1.2.1
        '@tailwindcss/vite': ^4.1.18
        '@vitejs/plugin-vue': ^6.0.1
        tailwindcss: ^4.1.18
        unplugin-auto-import: ^21.0.0
        unplugin-vue-components: ^31.0.0
        unplugin-vue-router: ^0.19.2
        vite: ^7.2.4
        vite-plugin-vue-layouts-next: ^1.3.0
        vue-macros: ^3.1.2
    dev:
        '@antfu/eslint-config': ^7.0.1
        '@tsconfig/node-ts': ^23.6.2
        '@tsconfig/node24': ^24.0.3
        '@tsconfig/strictest': ^2.0.8
        '@vue-macros/volar': ^3.1.2
        '@vue/test-utils': ^2.4.6
        '@vue/tsconfig': ^0.8.1
        ajv: ^6.14.0
        daisyui: ^5.5.14
        eslint: ^9.39.2
        eslint-config-prettier: ^10.1.8
        minimatch: ^10.2.1
        prettier: ^3.8.0
        typescript: ~5.9.3
        vite-bundle-analyzer: ^1.3.2
        vue-tsc: 3.0.8
    frontend:
        '@unhead/vue': ^2.1.2
        '@vueuse/core': ^14.1.0
        axios: ^1.13.5
        dayjs: ^1.11.19
        jwt-decode: ^4.0.0
        nprogress: ^0.2.0
        vue: ^3.5.24
        vue-router: ^4.6.4
        zod: ^4.3.5
    types:
        '@types/eslint-config-prettier': ^6.11.3
        '@types/node': ^24.10.1
        '@types/nprogress': ^0.2.3
        type-fest: ^5.4.1
onlyBuiltDependencies:
    - esbuild
