// Code generated by "stringer -type=Status -trimprefix=Status"; DO NOT EDIT.

package host

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusPending-0]
	_ = x[StatusRunning-16]
	_ = x[StatusShuttingDown-32]
	_ = x[StatusTerminated-48]
	_ = x[StatusStopping-64]
	_ = x[StatusStopped-80]
}

const (
	_Status_name_0 = "Pending"
	_Status_name_1 = "Running"
	_Status_name_2 = "ShuttingDown"
	_Status_name_3 = "Terminated"
	_Status_name_4 = "Stopping"
	_Status_name_5 = "Stopped"
)

func (i Status) String() string {
	switch {
	case i == 0:
		return _Status_name_0
	case i == 16:
		return _Status_name_1
	case i == 32:
		return _Status_name_2
	case i == 48:
		return _Status_name_3
	case i == 64:
		return _Status_name_4
	case i == 80:
		return _Status_name_5
	default:
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
