version: "2"
sql:
  - engine: sqlite
    queries: ../pkg/database
    schema: schema.sql
    gen:
      go:
        package: database
        out: ../pkg/database
        emit_interface: true
        emit_empty_slices: true
        emit_pointers_for_null_types: true
        output_db_file_name: db.sql.go
        output_models_file_name: models.sql.go
        output_querier_file_name: querier.sql.go
overrides:
    go: null
plugins: []
rules: []
options: {}
