name: build
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-2

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/herobrian:latest
        file: ./build/Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max


