name: build
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-2

    - name: Login to Amazon ECR Private
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and tag Docker image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: bdreece/herobrian
        IMAGE_TAG: ${{ github.sha }}
      run: docker build -f build/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

    - name: Push Docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: bdreece/herobrian
        IMAGE_TAG: ${{ github.sha }}
      run: docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

